# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d83742fbbbb4b641d17a470a5f84470e9b94fffce95fc6a571f4a775e30c80be9f5b7f41484ef270591096c76315c9f2aa32f4a9ead42ecc8debb15b8ac88f

test:
  secret_key_base: b69927510c873399710569db96ed05ca9b660737f1e4965f7a3497d364e0c9b87a9d543ea42ea3096d789ee60341e64927bbf4576c06abbe38aa14d6e2fa8cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
